name: Chocolatine
env:
      MIRROR_URL: ""
      EXECUTABLES: choco
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  check_program_cleanliness:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
          for FILES in $UNWANTED_FILES; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
          done
          if [[ -n $UNWANTED_FILES ]]
          then
            exit 1
          else
            echo No unwanted files detected
          fi
  check_program_compilation:
    needs:
      - check_program_cleanliness
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make
      timeout-minutes: 2
    - run: make clean
    - run: for FILE in $EXECUTABLES; do test -f $FILE && echo '$FILE exist' ; done
  run_tests:
    needs:
      - check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    steps:
    - uses : actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make tests_run    
      