name: Chocolatine
env:
      MIRROR_URL: ""
      EXECUTABLES: choco
on: 
  push:
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  check_program_cleanless:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: find -name '#*#' -o -name '*-' -o -name '*pain_au_chocolat*' -o -name '*.a' -o -name '*.o' -o -name '*.gcno' -o -name '*.gcda' -o -name '*.gcov'
  check_program_compilation:
    needs:
      - check_program_cleanless
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make
    - run: make clean
    - run: for file in $EXECUTABLES; do test -f $file && echo '$file exist' ; done
  run_tests:
    needs:
      - check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    steps:
    - uses : actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make tests_run    
      