name: Chocolatine
on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"  
jobs:
  check_program_cleanliness:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*tmp/*" -or -name "*~" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gdca" -or -name "*.gcov" -or -name "*pain_au_chocolat*")
          for FILES in $UNWANTED_FILES; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
          done
          if [[ -n $UNWANTED_FILES ]]
          then
            exit 1
          else
            echo No unwanted files detected
          fi
  check_program_compilation:
    env:
      EXECUTABLES: ${{ secrets.EXECUTABLES }}
    needs:
      - check_program_cleanliness
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make
      timeout-minutes: 2
    - run: make clean
    - run: for $FILE in $EXECUTABLES; do test -f $FILE && echo '$FILE exist' ; done
  run_tests:
    needs:
      - check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    steps:
    - uses : actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make tests_run    
  push_to_mirror:
    env:
      MIRROR_URL: ${{ secrets.MIRROR_URL }}
    needs: 
      - run_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.GIT_SSH_PRIVATE_KEY }}
