name: Chocolatine
env:
      MIRROR_URL: ""
      EXECUTABLES: choco
on: 
  push:
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  check_program_cleanless:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo 'CLEAN'    
  check_program_compilation:
    needs:
      - check_program_cleanless
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make
    - run: make clean
    - run: for file in $EXECUTABLES; do test -f $file && echo '$file exist' ; done
