name: Chocolatine
env:
      MIRROR_URL: ""
      EXECUTABLES: choco
on:
  pull-request:
    branches-ignore:
      - 'ga-ignore-*'
  push:
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  check_program_cleanliness:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: >
      find -name '#*#' -exec echo 'Unwanted file detected : {} \;' -o -name '*-' -exec echo 'Unwanted file detected : {} \;' -o -name '*pain_au_chocolat*' -exec echo 'Unwanted file detected : {}  \;'  -o -name '*.a' -exec echo 'Unwanted file detected : {} \;'  -o -name '*.o' -exec echo 'Unwanted file detected : {} \;'  -o -name '*.gcno' -exec echo 'Unwanted file detected : {} \;' -o -name '*.gcda' -exec echo 'Unwanted file detected : {} \;'  -o -name '*.gcov' -exec echo 'Unwanted file detected : {} \;'
  check_program_compilation:
    needs:
      - check_program_cleanliness
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make
      timeout-minutes: 2
    - run: make clean
    - run: for FILE in $EXECUTABLES; do test -f $FILE && echo '$FILE exist' ; done
  run_tests:
    needs:
      - check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    timeout-minutes: 2
    steps:
    - uses : actions/checkout@v2
      with:
        fetch-depth: 0
    - run: make tests_run    
      